Fix spaces for notify emails (issue #346)
geopython/GeoHealthCheck pull request #350
Opened 2021-04-15 20:12 UTC by borrob

The input for the email address for the notification allows for multiply
entries if they are separated by commas. When the form is displayed again,
spaces are added after the commas. The extra spaces generate an error when the
user tries to safe the edits.

This commit fixes:
- no spaces are added when the form is displayed again.
- removes spaces in the email address field before saving.

2021-04-22 13:58 UTC, justb4 requested changes
Although the fix in the client looks ok, server-side handling should not depend on it. The server that handles the form should strip any whitespace around email addresses before storing. 
The current code does not seem to do this see [app.py#L688](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L688). I think the code should be: `[v.strip() for v in value]` also on [L691](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L691). I think this server-fix(es) can be added in addition to the client template fix here.

2021-04-22 20:37 UTC, borrob commented
> Although the fix in the client looks ok, server-side handling should not depend on it. The server that handles the form should strip any whitespace around email addresses before storing.
> The current code does not seem to do this see [app.py#L688](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L688). I think the code should be: `[v.strip() for v in value]` also on [L691](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/app.py#L691). I think this server-fix(es) can be added in addition to the client template fix here.

Good catch on the back end. I added the `strip()` commands to `[v.strip() for v in value if v.strip()]`. The latter `v.strip()` is still necessary since it will catch 'empty' (i.e. just spaces) values. This prevents errors when an email list is entered as `a@mail.com, ,b@mail.com` (notice the `, ,` structure).

2021-04-23 10:53 UTC, justb4 approved these changes

2021-04-23 10:54 UTC, merged

2021-04-23 10:54 UTC, justb4 commented
Thanks @borrob !