Mbtiles Probe
geopython/GeoHealthCheck pull request #405
Opened 2021-11-04 10:14 UTC by jochemthart1

This PR adds a probe for Mapbox Vector tile service based on issue #380.

The tileset.json is requested and checked for http-errors. 

**Design:**
From the tileset.json, center coordinate and zoom levels are taken to be used in tile requests later on. If center coordinate doesn't exist, the bounds are used to calculate center coordinate. If bounds do not exist either, result is returned as false.

Then, multiple tile url's are constructed using the tile zoom level and center coordinate and are requested and checked for http-errors as well.

An additional check for http204 errors is implemented when requesting tile data, because a request on coordinates with no data would return an empty page.

2021-11-04 10:59 UTC, justb4 requested changes
Thanks @jochemthart1 . Also to @fsteggink : 
My main comment concerns naming/terminology: with "MBTiles" I think of the storage format for both Vector and Raster Tiles in SQLite. Also the [MB docs](https://docs.mapbox.com/help/glossary/mbtiles/#:~:text=MBTiles%20is%20a%20file%20format,from%20many%20different%20data%20sources.) says: _"MBTiles is a file format for storing tilesets. "_. Also MapProxy supports MBTiles file format.

A better naming, also as maybe MB may not be the maintainer in the future (viz MapLibre) **"TileJSON"** is a more adequate name for the web service. As it is also [named TileJSON in the spec](https://github.com/mapbox/tilejson-spec).

I understand this means a lot of renaming but also to avoid later confusion. I propose these name changes:

* `enum`: `MapBox:TileJSON`
* `GeoHealthCheck.plugins.probe.mbtiles.MBTiles` to `GeoHealthCheck.plugins.probe.mapbox.TileJSON`

2021-11-11 10:05 UTC, justb4 commented on GeoHealthCheck/healthcheck.py
> +                         'TileJSON': [urlopen],
Make consistent with (new) definition in `enum.py`: `Mapbox:TileJSON`

2021-11-11 10:09 UTC, justb4 requested changes
Main comment: make definition and its use consistent: `Mapbox:TileJSON`.

2021-11-11 10:09 UTC, justb4 commented on GeoHealthCheck/enums.py
> +    },
Official company name is `Mapbox` (not `MapBox`), make definition consistent: `Mapbox:TileJSON`.

2021-11-11 10:09 UTC, justb4 commented on GeoHealthCheck/plugins/probe/mapbox.py
> +    RESOURCE_TYPE = 'TileJSON'
Make `RESOURCE_TYPE` consistent: `Mapbox:TileJSON`

2021-11-11 10:09 UTC, justb4 commented on GeoHealthCheck/config_main.py
> +    },
Make consistent: `Mapbox:TileJSON`

2021-11-11 12:05 UTC, jochemthart1 commented
I think automatic checks are failing because of this resource not responding:
[https://geodata.nationaalgeoregister.nl/bag/wms/v1_1](https://geodata.nationaalgeoregister.nl/bag/wms/v1_1)

2021-11-11 16:13 UTC, merged

2021-11-12 10:40 UTC, justb4 commented
I am trying https://geodata.nationaalgeoregister.nl/beta/topotiles-viewer/styles/tilejson.json 
[on GHC demo](https://demo.geohealthcheck.org/resource/413), but this fails. It advertises v2.2.0. Or is there another root URL to be used?

2021-11-12 10:48 UTC, jochemthart1 commented
@justb4 I see.
In the design I went with getting the center of the map from the center attribute in the tilejson or from calculating the center from the bounds attribute. However, this endpoint does not seem to have either.

Not sure how I could determine the center tile for this endpoint. Do you have any suggestions?

I might have to add an exception clause there to make sure the error is more clear when this happens.

2021-11-12 11:34 UTC, justb4 commented
@jochemthart1 I am not so familiar with the TileJSON standard. Found another endpoint from Mapbox, also 2.2.0 with `bounds` but also fails on [GHC demo](https://demo.geohealthcheck.org/resource/414) with another reason: https://a.tiles.mapbox.com/v3/aj.1x1-degrees.json. 
Error `Perform_request Err: UnboundLocalError local variable 'wm_coords' referenced before assignment`.
Not sure what happens. You may consider using `pyproj` (included in GHC) for coordinate  transformation.


`bounds` and `center` are both optional in [the 2.2.0 TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0). Well, I should say bad luck then, or assume global bounds, but then other failures may arise.